# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': 'Evennia',
    'game_status': 'pre-alpha',
    'game_website': '',
    'listing_contact': 'm.tayag21@gmail.com',
    'long_description': 'Cooperative Gambiling based game for INST490 Capstone',
    'short_description': 'Game for INST490 Project',
    'telnet_hostname': '',
    'telnet_port': '4000',
    'web_client_url': ''}